spring:
  application:
    name: backend
  liquibase:
    enabled: false
  config:
    booking:
      workshops:
        - name: "Manchester"
          address: "14 Bury New Rd, Manchester"
          vehicleTypes:
            - "Car"
            - "Truck"
          enabled: true
          api: "http://localhost:9004/api/v2"
          serviceClass: "ManchesterBookingService"
        - name: "London"
          address: "1A Gunton Rd, London"
          vehicleTypes:
            - "Car"
          enabled: true
          api: "http://localhost:9003/api/v1"
          serviceClass: "LondonBookingService"
logging:
  level:
    root: INFO
    com.karmeb.app: DEBUG